### PR TITLE
Additions to franchise posters

### PR DESCRIPTION
**Pull request by TheChrisK**
I created some franchise posters using the default template for my personal collection. Sharing out if interested.

### CODE REVIEW

**Comment by bullmoose20** [comment]
Do you have the raw logos and color schemes you used for these?

We try to capture the logos and the color schemes so that in the future if we need to tweak  the defaults and make global changes we can automate it.

Thanks…
________________________________
From: Chris K ***@***.***>
Sent: Saturday, July 8, 2023 10:22:39 AM
To: meisnate12/Plex-Meta-Manager-Images ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [meisnate12/Plex-Meta-Manager-Images] Additions to franchise posters (PR #189)


I created some franchise posters using the default template for my personal collection. Sharing out if interested.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189

Commit Summary

  *   561a54c<https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189/commits/561a54ca63a25a65bde348064035a77644c2da16> add franchise posters
  *   1fc15af<https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189/commits/1fc15afe25014dd37e6529be3673fd3982feb9d7> revert Batman.jpg to original

File Changes

(7 files<https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189/files>)

  *   A franchise/BTTF.jpg<https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189/files#diff-6d0c49aced9ca552818e9c0009859fee5b94a6d5c4ea5a9ef1e4bebc16f855ab> (0)
  *   A franchise/Blade.jpg<https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189/files#diff-f010c102c1cd8c804d55a678bb09a68c454cc75bb9cb3c319ef44df2b28ab7d9> (0)
  *   A franchise/Dark Knight.jpg<https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189/files#diff-62ba6ec8dca91fb6c3af02be8d31edcc0356c30201a4fd736fe91cb9121856d7> (0)
  *   A franchise/Godfather.jpg<https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189/files#diff-a4b548b4e13a0e760d384c98432c78b15d8a52a1421c0bcba74232fb80e0d380> (0)
  *   A franchise/Robocop.jpg<https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189/files#diff-5576155a700bfb69cce1892a890c20926b71bd163f2dd133099fc66c0c1fdb17> (0)
  *   A franchise/Terminator.jpg<https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189/files#diff-3042133c45285aba41bfc341808681796ac2e5360ba718605fd6aedac06d9d05> (0)
  *   A franchise/Transporter.jpg<https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189/files#diff-1ddc498e0a06ce984515d3ceced3a034806d1da5c7f83a12a5ab35e04eefb4e4> (0)

Patch Links:

  *   https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189.patch
  *   https://github.com/meisnate12/Plex-Meta-Manager-Images/pull/189.diff

**Comment by TheChrisK** [comment]
I have the logos, yes. The color scheme is the default from the [psd](https://github.com/meisnate12/Plex-Meta-Manager-Images/blob/master/Defaults_Template.psd) provided in this repo.

**Comment by TheChrisK** [comment]
Added logos to PR.

**Comment by bullmoose20** [comment]
OK. So you picked some colors already in there.... I ask because the theme actually tends to randomize the color of the background so that they are all unique. If you are not attached to any of the background colors, we can have the script create some on the fly. If you join our Discord server, we can collaborate on the colors and then set it and forget it. Let us know.

Thanks for the logos as I will review and run some tests.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TheChrisK** [comment]
Thank you. Yes the colors were either default Plex, Trakt or RT with a few being custom by just adjusting hue, saturation, etc... I did not save them and any future random colors would be fine. No rhyme or reason.

**Comment by bullmoose20** [comment]
In logos, I see 007, however we already have that logo and poster as part of the franchise folder. I see the Transporter poster, however the logo is missing. Dickhouse logo is missing as well. Wouldn't the Batman franchise cover "Dark Knight" that you submitted?

**Comment by TheChrisK** [comment]
Sorry about that. 

- I created my own 007 poster and added it in haste. I will remove that one. 
- The Transporter logo is just a font but I will add it as a logo.
- Dickhouse will be added as well.

The Dark Knight Trilogy is for the Christian Bale series of Batman films. I created one separately for the Keaton/Kilmer/Clooney Batman films but I saw that it would overwrite an existing poster so I removed it.

**Comment by TheChrisK** [comment]
I forgot about this. Anything else needed?

**Comment by TheChrisK** [comment]
Resolving via discord.

**Pull request closed without merging**
